# Generated by Django 4.1.7 on 2023-04-04 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_volunteer_customuser_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ClientProfile',
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='users_images', verbose_name='картинка')),
                ('age', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(130)], verbose_name='возраст')),
                ('sex', models.SmallIntegerField(blank=True, choices=[(0, 'Мужской'), (1, 'Женский')], null=True, verbose_name='пол')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='регион')),
                ('about_me', models.TextField(blank=True, default='', max_length=600, verbose_name='о себе')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='оценка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.volunteer')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
                'abstract': False,
            },
        ),
    ]
