# Generated by Django 4.1.7 on 2023-04-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_clientprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cl_profile', to='users.client'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vol_profile', to='users.volunteer'),
        ),
    ]
