# Generated by Django 4.1.7 on 2023-04-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_clientprofile_user_alter_volunteerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('VOL', 'Волонтер'), ('CL', 'Клиент')], max_length=50),
        ),
    ]
