# Generated by Django 4.1.7 on 2023-04-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('VOL', 'Волонтер'), ('CL', 'Клиент')], max_length=50),
        ),
    ]
