# Generated by Django 4.1.7 on 2023-04-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_clientprofile_mobility'),
        ('orders', '0002_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.volunteer', verbose_name='волонтер'),
        ),
    ]
