# Generated by Django 4.1.7 on 2023-04-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_clientprofile_mobility'),
        ('orders', '0003_order_client_order_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_orders', to='users.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_orders', to='users.volunteer', verbose_name='волонтер'),
        ),
    ]
